import pandas as pd

def excel_column_to_index(col_label):
    """Converts Excel column label (e.g., 'A', 'Z', 'ML') to 0-based index."""
    index = 0
    for char in col_label.upper():
        index = index * 26 + (ord(char) - ord('A') + 1)
    return index - 1

def trim_hwinfo_csv(input_path, output_path, keep_cols):
    """
    Docstring for trim_hwinfo_csv
    
    :param input_path: Relative path from script to HWiNFO logging file generated by run_mlc_and_log.py
    :param output_path: Relative path from script to save trimmed HWiNFO logging file
    :param keep_cols: A list of column ranges to keep, separated by hyphen (inclusive). E.g., ['C-H', 'J-Z'] keeps columns C to H and J to Z.
    """
    print(f"[*] Loading {input_path}...")
    
    try:
        df = pd.read_csv(input_path, encoding='latin-1', low_memory=False)
    except Exception as e:
        print(f"Error reading CSV: {e}")
        return
    print("Successfully loaded {} with {} columns.".format(input_path, len(df.columns)))

    cols_to_drop = []

    # keep_cols is a list of ranges (e.g. [A-C, J-Z]), isolate the columns to drop

    for i, interval in enumerate(keep_cols):
        start_col, end_col = interval.split('-')

        # get the first column to cut (end_col + 1)
        cut_start_idx = excel_column_to_index(end_col) + 1
        if (i != len(keep_cols) - 1):
            # if not the last interval, cut until the start of the next interval
            next_start_col = keep_cols[i + 1].split('-')[0]
            cut_end_idx = excel_column_to_index(next_start_col) - 1
        else:
            # if last interval, cut until the end
            cut_end_idx = len(df.columns) - 1

        cols_to_drop.extend(df.columns[cut_start_idx : cut_end_idx])
        # print(f"[*] Dropping {len(cols_to_drop)} columns (from {cut_start_idx} to {cut_end_idx})...")
        
    print("cols to drop:", cols_to_drop)

    # 3. Drop and Save
    df_trimmed = df.drop(columns=cols_to_drop)
    df_trimmed.to_csv(output_path, index=False)
    
    print(f"[+] Success! Trimmed file saved to: {output_path}")
    print(f"    Remaining columns: {len(df_trimmed.columns)}")

if __name__ == "__main__":
    import argparse
    
    parser = argparse.ArgumentParser(description="Trim HWiNFO CSV logs by removing specified columns.")
    parser.add_argument("--input-path", type=str,
                       help="Path to HWiNFO CSV file with empirical power measurements")
    parser.add_argument("--output-path", type=str,
                       help="Path to save the trimmed HWiNFO CSV file")
    parser.add_argument("--keep-cols", nargs='+', type=str,
                        help="List of column ranges to keep, separated by hyphen (inclusive). E.g., C-H J-Z keeps columns C to H and J to Z.")
    
    args = parser.parse_args()

    if (not args.input_path) or (not args.output_path) or (not args.keep_cols):
        print("Error: Please provide --input-path, --output-path, and --keep-cols arguments.")
        exit(1)
    
    trim_hwinfo_csv(
        input_path=args.input_path, 
        output_path=args.output_path,
        keep_cols=args.keep_cols
    )
    